### ISSUE TITLE
Very long filenames

### ISSUE THREAD

**Issue by Nissemus** [TheKonka/instagram-download-browser-extension#1]
The extension is currently generating filenames such as:
"358566487_636829371499134_623616662404784974_n.jpg stp=dst-jpg_e35_p1080x1080&_nc_ht=scontent-lhr8-1.cdninstagram.com&_nc_cat=106&_nc_ohc=GCZr33oTVZkAX8m-8HI&edm=ANmP7GQBAAAA&ccb=7-5&ig_cache_key=MzE0Mjg5Mj"

This is probably caused by a code change by Instagram.

**Comment by TheKonka** [comment]
Thanks for the feedbackt! It was fixed in the latest version(v1.2.9).
