### ISSUE TITLE
Download icon missing from Stories

### ISSUE THREAD

**Issue by Nissemus** [TheKonka/instagram-download-browser-extension#10]
As of today the download icon no longer appears in Stories, meaning that pics and videos can't be downloaded.

**Comment by sn3akyb3ar** [comment]
The icon appears for me, but it does nothing.

**Comment by Nissemus** [comment]
If you Stories open and use Duplicate Tab, it works in the new tab, so that's a workaround.

**Comment by TheKonka** [comment]
I have update the addon yesterday. You can try the latest version to see whether the problem still exists.

**Comment by Nissemus** [comment]
Unfortunately the problem is still there.

**Comment by TheKonka** [comment]
> Unfortunately the problem is still there.

Can you give me a link to reproduce the problem? I can't reproduce it on my end.

**Comment by Nissemus** [comment]
> Can you give me a link to reproduce the problem? I can't reproduce it on my end.

Here's an example: if you go to https://www.instagram.com/thewarningargentina/ and click on their Stories link, the download icon doesn't appear. If you can't reproduce this, there must be something weird in my Firefox settings that's causing it.

Something *has* changed, though — I've now found that if I do that and then press Refresh, the icon shows up! So if it's not fixable, I guess I can live with that.

**Comment by TheKonka** [comment]
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/b51d7e7d-18d7-43b5-900c-de633d327275)

I have the icons without refreshing the tab. If the Firefox add-on version your are using is the latest(1.3.7), I don't know the exact cause of the problem at the moment...

**Comment by sn3akyb3ar** [comment]
> I have the icons without refreshing the tab.

Check the stories, not the highlights. Maybe it's somehow related to the fact that when you open the stories from the account page, the story link looks like this: https://instagram.com/stories/%username%. However, when you open it from your feed, it also shows the numerical ID of the story in the link, like this:

![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/34551334/60c319bc-37be-4d13-894e-2fc5252e2a56)

I just checked version 1.3.7, and both the "download" and "open in a new tab" buttons don't work if the link doesn't contain that ID.

**Comment by TheKonka** [comment]
@sn3akyb3ar  Oh, I thought there would always be an id. Because even if I open the stories from the account page, there is an id in the link address.  Also, when I click the prev or next button to switch stories, the id changes at the same time. Actually I don't use Instagram very often, so there are a few I may not have come across.

**Comment by sn3akyb3ar** [comment]
> Also, when I click the prev or next button to switch stories, the id changes at the same time

Yes, it does change when you switch stories. But buttons don't appear until you reload the page. Maybe Instagram tests it for different users.

**Comment by TheKonka** [comment]
I've updated a new version. Hope it can fix the problem.

**Comment by Nissemus** [comment]
That seems to have fixed it. Good job!

**Comment by Nissemus** [comment]
Closing this.
