### ISSUE TITLE
Stories in DMs

### ISSUE THREAD

**Issue by sn3akyb3ar** [TheKonka/instagram-download-browser-extension#17]
I noticed that when you open a story shared with you via Direct Messages, downloader either doesn't download anything, or it downloads one of three things - 1) your own story, 2) text file with your username (I forgot to copy what was in it), 3) the last story you saw (or last one you downloaded? not sure). It works correctly after refreshing the page.

**Comment by TheKonka** [comment]
Please try the latest version(v2.0.2) to see whether the problem still exists.

**Comment by sn3akyb3ar** [comment]
@TheKonka 

Yep, the problem still persists. 

I did some quick testing:

1) I sent Luna Blaise's story to myself from my second account and opened it from Direct - it was saved without any problems.
2) Then I asked a friend to DM me any story - addon saved Luna's story again.
3) Opened some stories from my feed - all saved with no problems.
4) Opened some stories from personal pages - and that's where it gets more weird.
       a) if they have only one story or if it's the first story - it still downloads Luna's story. All subsequent stories are downloaded as intended. If I switch to second story and then back to the first one. it's also downloaded as intended lol.
       b) but if I saw some of their stories before and I open their second story - downloader doesn't download neither the opened story nor Luna's (until refreshing or switching to next story and back.)

Tested on Thorium 119 x64, but I'll check on clean Firefox and let you know if it still happens there.

**Comment by sn3akyb3ar** [comment]
Strange. Restarted browser and tried again - and even after restart it still downloads Luna's story. Also, this thing happens a lot lately:
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/34551334/9f84bfd2-3e47-4140-be0d-3867c7a75754)
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/34551334/999139c6-36ad-42a0-9004-075bebcdbbef)

**Comment by RVC2020** [comment]
I also have the 2nd problem. For me, it started after updating to v2.0.4.

![2024-02-28_20-24](https://github.com/TheKonka/instagram-download-browser-extension/assets/75840436/976d429e-848e-48a6-8c00-d90d496aa4d9)

**Comment by sn3akyb3ar** [comment]
Closing this, I think it was fixed a while ago. At least I haven't seen such behaviour for some time.
