### ISSUE TITLE
Option to hide/disable the "open in new tab" icon

### ISSUE THREAD

**Issue by parasiteoflife** [TheKonka/instagram-download-browser-extension#19]
Basically title, I have no use for it and more often than not I keep pressing it by mistake, please add an option to hide it or disable it.

**Comment by TheKonka** [comment]
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/b9adc9b4-ea61-4369-9550-951d4edf4235)
Thanks for your feedback, the latest version(v2.0.2) already supports this feature!
