### ISSUE TITLE
Instagram has changed the layout post when clicked

### ISSUE THREAD

**Issue by HuskyZa** [TheKonka/instagram-download-browser-extension#21]
This extension is not working for a post when click from 
1.  a user's profile page, or
2. from a saved collection

Here's an example of a new IG layout where this extension will not work.
<img width="1274" alt="Screenshot 2024-03-06 213401" src="https://github.com/TheKonka/instagram-download-browser-extension/assets/5336912/fb872a8f-3320-4582-b58b-7a868393b2c">

The extension is working fine for
1. stories
2. post on a news feed

**Comment by TheKonka** [comment]
It's still the old layout on my end for now 🤔, I'll try to fix this when I see the new layout.
