### ISSUE TITLE
Feature Request: Download a reel thumbnail

### ISSUE THREAD

**Issue by sn3akyb3ar** [TheKonka/instagram-download-browser-extension#22]
Just like the title says: do you think it's possible to add an option to download thumbnails from reels? Some people use unique pictures for them.

**Comment by TheKonka** [comment]
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/6544b9b8-3366-487f-942e-c011d627b879)
Hello, is that what you mean? The latest version already supports this.

**Comment by sn3akyb3ar** [comment]
Oh, okay, then I'm closing the issue, I didn't notice :)
