### ISSUE TITLE
Cannot download non-first photos/videos in a post

### ISSUE THREAD

**Issue by HuskyZa** [TheKonka/instagram-download-browser-extension#23]
When there are multiple photos or videos in a single post, the downloader can only download the first photo/video even navigate to other media in that post.

**Comment by TheKonka** [comment]
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/0dc50a83-428d-4d91-b29e-adf6e4a5b746)

I've temporarily rolled back to previous version 2.0.5 on Firefox. And the latest version 2.0.7 is under review. If your version is still 2.0.6. Try reinstall the add-on.
