### ISSUE TITLE
Instagram blocking extension?

### ISSUE THREAD

**Issue by Allen-Kwan** [TheKonka/instagram-download-browser-extension#25]
Hi there, not sure if anyone has the same issue but today Instagram seems to be blocking access to individual profile pages with the extension on.  Turning it off allows access to the profiles.  The extension still works in the main feed at least, but that's the only page that can be navigated.

This is what I see on any profile page:
![cDkMovd 1](https://github.com/TheKonka/instagram-download-browser-extension/assets/54609347/ee4c95e7-af1e-4a25-bb61-076d27308db0)

Not sure if it needs to be updated?

**Comment by Nissemus** [comment]
I have this with version 2.0.7 on Chrome. 
https://www.instagram.com/thewarningrockband/

**Comment by TheKonka** [comment]
Thanks for the feedback, I apologize for the bug, this issue only occurs in chrome, I've been using Firefox lately so I didn't notice it. I've submitted version 2.0.8 for review, please wait!

**Comment by Allen-Kwan** [comment]
Thank you!
