### ISSUE TITLE
Download button not shown on videos

### ISSUE THREAD

**Issue by ghost** [TheKonka/instagram-download-browser-extension#28]
Browser(Chrome/Firefox): Firefox 125.3.0 on Android
Extension Version: 2.1.2
Reproduction of links: Can't share because account private and NSFW, and they will only approve those with same interests. 

Download button does not show on videos if the account is private. it works fine with pictures

**Comment by TheKonka** [comment]
Thanks for your feedback! 
I have updated a new version(2.1.3) to fix it. 
You can try it on Chrome now.
It is still under review on Firefox.
