### ISSUE TITLE
Story download icons not appearing

### ISSUE THREAD

**Issue by xewwon** [TheKonka/instagram-download-browser-extension#33]
The download and open in new tab icons, no longer appear on stories.
They are visible in other locations like posts still.

Browser: Chrome
Extension version: 2.2.0

<img width="187" alt="image" src="https://github.com/user-attachments/assets/922df292-5dcc-4adc-852c-8973ba23629d">
Normally the icons would be right under the name display.

**Comment by lewislarsen** [comment]
Experiencing the same problem on Firefox. 

You can still right click and open the images in a new tab etc, but saving video stories isn't possible at the moment.

**Comment by TheKonka** [comment]
Thanks for the feedback, I've submitted a new version 2.2.1 to fix this. Chrome usually reviews within a day, but Firefox takes about a week.

**Comment by nifoc** [comment]
> Thanks for the feedback, I've submitted a new version 2.2.1 to fix this. Chrome usually reviews within a day, but Firefox takes about a week.

Thank you for the quick turnaround!

Could you maybe push the updated source code, so that (those interested) can build the extension locally? (Until an updates arrives on AMO in my case)
