### ISSUE TITLE
Instagram Story Download Icon not working

### ISSUE THREAD

**Issue by ItsmeChaz** [TheKonka/instagram-download-browser-extension#34]
Browser(Chrome/Firefox):  Firefox
Extension Version:  115.15.0.esr
Reproduction of links:  

On Instagram Stories, the download icon appears but it does not work when clicking on the download icon; there is no download.  I have received this error on numerous Instagram Stories.  The download icon still works with the photos within the Instagram account.

**Comment by ItsmeChaz** [comment]
Is no one else experiencing the same problem while using the Firefox browser???

**Comment by ItsmeChaz** [comment]
The Instagram Story Download Icon when using the Firefox browser appears to be working again.  What was more disappointing is that no one even took the time to respond to my original post, including no response from TheKonka.

**Comment by TheKonka** [comment]
Sorry for the delayed reply, I'm recently unemployed and looking for a job, and I cannot reproduce this issue on my end at the moment, so I can't concentrate on it for a while, and it just so happens that there was a recent update, so I thought maybe the new version(2.2.2) would be the right one to fix it, so I didn't get back to you right away. Anyway, I'm glad that the plugin works again.

**Comment by ItsmeChaz** [comment]
> Sorry for the delayed reply, I'm recently unemployed and looking for a job, and I cannot reproduce this issue on my end at the moment, so I can't concentrate on it for a while, and it just so happens that there was a recent update, so I thought maybe the new version(2.2.2) would be the right one to fix it, so I didn't get back to you right away. Anyway, I'm glad that the plugin works again.

TheKonka, please allow me to apologize for my overdue response to your message.  I really appreciate you taking the time to respond to my original post.  I'm sorry to hear about your employment status - I hope your situation will improve.  I don't know what was going on, but it appeared to be a periodic glitch with the Firefox browser.  However, I am glad it's finally working again.  Thanks for all your work on this app for both the Firefox and Chrome browsers!
