### ISSUE TITLE
No sound in videos

### ISSUE THREAD

**Issue by sn3akyb3ar** [TheKonka/instagram-download-browser-extension#37]
Seems like instagram (or addon update?) changed something and all videos (in posts, stories and reels) now have no sound. Addon v2.2.3

**Comment by Nissemus** [comment]
Sound is ok here.

**Comment by sn3akyb3ar** [comment]
> Sound is ok here.

Just tested a bit more, and it seems like it works in Chromium-based browsers, but doesn't work in Firefox. Some of videos downloaded in Fx had sound, but most of them didn't.

**Comment by sn3akyb3ar** [comment]
Seems like it was some bug on Instagram side, everything works fine now. I guess I'll wait a few days before closing the issue just to make sure.
