### ISSUE TITLE
Permissions tweak for Android

### ISSUE THREAD

**Issue by Jon8RFC** [TheKonka/instagram-download-browser-extension#4]
Thanks for making this.  It's very handy.

I'm using this on Android following [these instructions](https://www.androidpolice.com/install-add-on-extension-mozilla-firefox-android/).

I see that only two permissions are listed rather than three, and the option to toggle permissions for add-ons doesn't seem to exist in firefox beta for android:
Access your data for www.instagram.com
Store unlimited amount of client-side data

However, maybe there is a way around it.

[media-helper](https://github.com/mittya/media-helper) also suffers, but partially works for some reason.
I can tap & hold, and that add-on enables the context menu on an image and I can save or open in a new tab on android.  But its javascript-added button also doesn't function.

If I were to manually edit some files in the .xpi, what would I want to add to which file, so that I can manually/forcibly enable the missing permission for https://*instagram.com?

Better yet, [maxurl](https://github.com/qsniyg/maxurl) doesn't seem restricted from creating its pop-ups, possibly because of the permission "allow access to all sites" and it's also not a toggle I can enable, but it's already enabled by default.
What would I change to force "allow access to all sites" for your add-on?

That may be the ticket to success on android--allowing access to all sites by default.

**Comment by TheKonka** [comment]
Well, it seems my extension currently not supported running in Firefox for Android.

https://discourse.mozilla.org/t/blog-post-manifest-v3-in-firefox-recap-next-steps/97372/7
https://discourse.mozilla.org/t/request-permissions-at-install-time-manifest-v3/121543
https://discourse.mozilla.org/t/mv3-extension-not-working/107982/4
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/908d8c99-b9b9-4a67-a94f-42d15db19b4a)
The main reason may be I use MV3 instand of  MV2. And users need to grant the permissions manually as I noticed in [README](https://github.com/TheKonka/instagram-download-browser-extension/blob/master/README.md).
However,there are no way to set the permissions on Android at this time.

**Comment by Jon8RFC** [comment]
Very informative. Thank you for looking that up and sharing it all.

It's not only helpful information for this specific scenario, but also for me to better understand extensions/add-ons and tinkering in various browsers. I didn't know much other than "v2 is going away in chrome" as add-ons disappear or are no longer maintained. 

Just since we're on the topic and to keep things together for future Google searches and my own understanding...
I found this related to [converting manifests](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/GMWU8ZDALSs), based on what you've shown me. In the third post, they said the tool can convert go back and forth. The tool mentions that underlying manual code changes will still be necessary, but I can attempt it with simpler extensions/add-ons just to begin learning by doing. Thanks!

**Comment by TheKonka** [comment]
The latest version already supports Android.
