### ISSUE TITLE
Instagram has increased hostility - forced logouts whilst using this tool.

### ISSUE THREAD

**Issue by lewislarsen** [TheKonka/instagram-download-browser-extension#5]
I have used this plugin for a while to download content from Instagram, For the past 2-3 days now my account has been constantly logged out and I got a message stating that Instagram believes I'm using automated tooling.

I disabled the plugin on my Firefox browser earlier and knock on wood I haven't had any logouts. They were immediately logouts as well, as soon as I clicked on a story or navigated to another page I wouldn't be logged in anymore.

I did notice that when I was getting logged out, I was getting "__coig_restricted" appended to my URL as well - Any theories as to what that could stand for?

I don't use any other tool to download Instagram content, so all theories point to Instagram's increased hostility towards download tools and somehow they're detecting the changes the plugin makes to the page. (I would be interested in knowing how they're detecting this, since as far as I know the plugin is just putting pieces together that have already loaded and sending them to the file system.)

I would be interested in hearing if anybody else has had a similar experience, It seems like Instagram's restrictions are only worsening over time, unfortunately.

This isn't meant to scare anybody either, I'm only looking to raise awareness and perhaps find a solution to avoid any permanent account suspensions.

**Comment by amiga-500** [comment]
Oddly i have never experienced this and ive used this plugin from the beginning.

**Comment by Barracuda1337** [comment]
me to
I keep getting this error. and I think I got this error because it changed the structure of the videos and images on the home page. I hope that if the videos on the page appear normally and only the download button appears, this error will not occur.
